### ISSUE TITLE
BetterNether foliage stops generating if 256 nether is enabled.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Nether-API#11]
Tested with and without other Nether mods, same issue.

**Comment by jbredwards** [comment]
After testing, the only foliage not generating above 128 is the "betternether:stalagnate" plants (which is a bug, and will be fixed), but everything else appears to be generating fine. Is this the case for you as well, or is nothing generating in the biomes at all?

**Comment by MagmaBro123** [comment]
Bone Reef won't generate with the 256 option enabled. Without it enabled, this would locate just fine.
![2024-12-26_11 53 10](https://github.com/user-attachments/assets/0e8f5dab-8920-4557-a570-2b335156f9c4)

**Comment by MagmaSlime123** [comment]
It seems BetterNether biomes do generate, but BetterNether only lets you choose 0.0 to 1.0. With NetherAPI these biomes become SUPER rare, which confused me.

1.0 is supposed to mean very common, so whatever this mod is changing the weights to, I have no way of fixing this.

![image](https://github.com/user-attachments/assets/14168b91-03fd-47bc-ad3e-793a0a49ff05)

Also, Stalagnate generates just fine (Unless there's some bug I'm not aware of).

![2024-12-26_12 08 27](https://github.com/user-attachments/assets/081345f4-74d7-4ee3-bcf1-01e5547fe615)

**Comment by jbredwards** [comment]
> It seems BetterNether biomes do generate, but BetterNether only lets you choose 0.0 to 1.0. With NetherAPI these biomes become SUPER rare

The biome density config settings don't control biome weights, they determine how tightly packed together the BetterNether world features can generate in each biome (I can definitely see the confusion though). The original BetterNether mod has no config to determine biome weights, but it does have a biome toggle config. So I had to improvise and decided to just set the biome weight to 1 for each biome that's enabled (which is the default value in BetterNether ROTN and BetterNether Continuaion). I can't change this because it would mess up existing worlds.

> I have no way of fixing this

There are two forks of BetterNether that Nether API supports, [BetterNether ROTN](https://www.curseforge.com/minecraft/mc-mods/betternether-rotn-edition) and [BetterNether Continuation](https://modrinth.com/mod/betternether-continuation), which do offer configs for biome weights (hence why I haven't added a biome weight config for BetterNether from my end). You can either: switch to one of those and make each biome more common, or set the vanilla hell biome weight to 1 to make it as common as the BetterNether biomes.

**Comment by MagmaSlime123** [comment]
Ah, found the weight options. I was using Continuation, but wasn't aware both forks did that.

So, my bad.
