### ISSUE TITLE
Incompatible with Better Biome Blend

### ISSUE THREAD

**Issue by Michael-Sebero** [jbredwards/Nether-API#5]
https://www.curseforge.com/minecraft/mc-mods/better-biome-blend

Better Biome Blend is no longer functional when Nether API is installed.

**Comment by jbredwards** [comment]
This is not a Nether API issue, it's a Better Biome Blend issue. But it looks like they've fixed it in [this commit](https://github.com/FionaTheMortal/better-biome-blend/commit/7b76eb953c684938000b5278c281090d66730183) for an unreleased update. It's also been fixed in [MixinBooter v9.4](https://modrinth.com/mod/mixinbooter/version/9.4).
